-- Users
CREATE TABLE app_user (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  phone_e164 VARCHAR(20) NOT NULL,
  full_name VARCHAR(120),
  role ENUM('FARMER','BUYER','ADMIN') NOT NULL DEFAULT 'BUYER',
  whatsapp_opt_in TINYINT(1) NOT NULL DEFAULT 1,
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  CONSTRAINT uq_user_phone UNIQUE (phone_e164)
);

-- Master crop
CREATE TABLE crop (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(120),
  default_unit ENUM('KG','BAG','CRATE','BUNCH','TON') NOT NULL DEFAULT 'KG',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_crop_name UNIQUE (name)
);

-- Listing
CREATE TABLE listing (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  farmer_id BIGINT UNSIGNED NOT NULL,
  crop_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(160) NOT NULL,
  description TEXT,
  unit ENUM('KG','BAG','CRATE','BUNCH','TON') NOT NULL,
  quantity_available DECIMAL(12,3) NOT NULL,
  min_order_qty DECIMAL(12,3) NOT NULL DEFAULT 1.000,
  price_per_unit_ngn DECIMAL(12,2) NOT NULL,
  location_text VARCHAR(200),
  lat DECIMAL(10,7),
  lng DECIMAL(10,7),
  status ENUM('DRAFT','ACTIVE','SOLD_OUT','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  featured_until TIMESTAMP NULL,
  photos_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (farmer_id) REFERENCES app_user(id),
  FOREIGN KEY (crop_id) REFERENCES crop(id),
  INDEX idx_listing_status_crop (status, crop_id)
);

-- Order (quoted keyword)
CREATE TABLE `order` (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  buyer_id BIGINT UNSIGNED NOT NULL,
  farmer_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  quantity_ordered DECIMAL(12,3) NOT NULL,
  unit_price_snapshot DECIMAL(12,2) NOT NULL,
  subtotal_ngn DECIMAL(12,2) NOT NULL,
  platform_fee_ngn DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_ngn DECIMAL(12,2) NOT NULL,
  payment_method ENUM('COD','PAYSTACK','FLUTTERWAVE') NOT NULL DEFAULT 'COD',
  payment_status ENUM('UNPAID','PAID','REFUNDED') NOT NULL DEFAULT 'UNPAID',
  order_status ENUM('PENDING','CONFIRMED','CANCELLED','FULFILLED') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (buyer_id) REFERENCES app_user(id),
  FOREIGN KEY (farmer_id) REFERENCES app_user(id),
  FOREIGN KEY (listing_id) REFERENCES listing(id),
  INDEX idx_order_buyer_status (buyer_id, order_status)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Inside V1__init.sql, after creating `order` (with id BIGINT UNSIGNED)
CREATE TABLE payment (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  provider ENUM('PAYSTACK','FLUTTERWAVE') NOT NULL,
  provider_ref VARCHAR(120) NOT NULL,
  amount_ngn DECIMAL(12,2) NOT NULL,
  status ENUM('INITIATED','SUCCESS','FAILED','REFUNDED') NOT NULL DEFAULT 'INITIATED',
  paid_at TIMESTAMP NULL,
  raw_payload_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_payment_provider_ref UNIQUE (provider, provider_ref),
  CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES `order`(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
